# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeniorProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeniorProject
  pod 'Parse'
  pod 'ParseUI'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'Parse/FacebookUtils'
  pod 'Parse/TwitterUtils'
  pod 'PureLayout'
  pod 'LocationPicker'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'LocationPickerViewController'
  pod 'JSQMessagesViewController'
  pod 'Alamofire'
  pod 'ProgressHUD'
end
